In [4]:
#numpy is List
#Because
#   1. Faster
#   2. More functions that facilitate data science

import numpy as np

In [5]:
python_list = [1,2,3]

#Convert this to a numpy list
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [12]:
#One theory: one numpy can support only one type of data
#Python list supports many types of data

my_list = [1, "Hello", True, 1.0]
my_list = [1,2,3,4.5]

np_list = np.array(my_list) # All values becomes float
np_list

array([1. , 2. , 3. , 4.5])

In [13]:
#We can convert the type
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [14]:
#Acessing and indexing
#1 - Index
x = np.array([1,2,3,4,5,6,7,8]) # x = np.arryay(range(1,9))
x[2]

3

In [15]:
#2 - Slicing - get more than one number
#format array[start:end:step] - end is exclusive

x[0:3]


array([1, 2, 3])

In [18]:
#Get 3-8
#Method 1
x[2:8]
#Method 2
x[2:] 
#Method 3 - No
x[2:-1] 

array([3, 4, 5, 6, 7])

In [21]:
#Get 7,8 using minus
x[-2:]

array([7, 8])

In [23]:
#3 - Fancy indexing
#Sometimes I want index 2,4
x[2], x[4]

#put a list of inex you want to access
x[[2,4]]

array([3, 5])

In [26]:
#2D arrays

data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
#Format when you are dealing with multi-dim array
#array(dim1, dim2, so on....)
data
np_list[0,1] # Value 2
np_list[2,1] # Value 6

6

In [35]:
#Get [3,4], [5,6]
#Method 1 - Slicing
np_list[1: ,:]

array([[3, 4],
       [5, 6]])

In [36]:
#Method 2 - Fancy Indexing
np_list[[1,2],:]

array([[3, 4],
       [5, 6]])

In [38]:
#Method 3 - Last2
np_list[-2:,:]

array([[3, 4],
       [5, 6]])

In [42]:
data

[[1, 2], [3, 4], [5, 6]]

In [47]:
#Get 1, 3

np_list[0:2, 0]


array([1, 3])

In [52]:
#Get 1,5 
#Method 1 - Fancy indexing
np_list[[0,2],0]

#Method 2 - Use [start:end:step]
np_list[0::2,0]

array([1, 5])

In [70]:
x = [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]]
np_x = np.array(x)

#Get 2,6,10,14
np_x[:,1]

#Get, 7, 11
np_x[[1,2],2]
np_x[1:3,2]

#Get 4,7,10 - Hint use fancy indexing on both diamentions
np_x[[0,1,2],[3,2,1]]
#np_x[0:3, [3,2,1]]

#Get 16,15,14,13 - hint use step -1
np_x[-1,::-1]


array([16, 15, 14, 13])

In [50]:
#Exercise
#Given a matrix = [[99,99,99],
#                  [99,99,99],
#                  [99,99,99]]
#Imagine 99 is empty
#Assume 1 is X
#Assume 0 is O

#Get the input from X side and O side alternatively
#Give you a tuple of index

matrix = [[99,99,99],
          [99,99,99],
          [99,99,99]]

np_matrix = np.array(matrix) 

      

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])