In [1]:
import numpy as np

y = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
]

#1. 4,5,6
#2. 2,5
#3. 3,4
#4. 9,6,3

np_y = np.array(y) 
#format np_y[dim1, dim2]
print(np_y[1, :]) #1.

print(np_y[0:2, 1]) #2. method1
print(np_y[[0,1], 1])#2. method2

print(np_y[[0,1], [2, 0]]) # 3. dim1, dim2 both fancy indexing

row = [0,1]
column = [2, 0]
print(np_y[row, column]) # 3. dim1, dim2 both fancy indexing method2


print(np_y[::-1, 2]) # 4. method1

row = [2,1,0]
column = [2]
print(np_y[row, column])# 4. method2


[4 5 6]
[2 5]
[2 5]
[3 4]
[3 4]
[9 6 3]
[9 6 3]


Masking

In [2]:
x = [1,2,3,4,5,6,7,8,9,10]

#Need only the even numbers

#Method 1
even = []

for num in x:
    if num % 2 == 0:
        even.append(num)

print(even)

#Method 2 - List comprehension

even  = [num for num in x if num % 2 == 0]
print(even)

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]


In [3]:
np_x = np.arange(10) # this is range(10)

np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np_x[np_x % 2 == 0] # Actually this is fancy indexing

np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [5]:
np_x
ix = [ True, False,  True, False,  True, False,  True, False,  True,
       False]
np_x[ix]       

array([0, 2, 4, 6, 8])

In [6]:
#Chose odd numbers from np_x less than 5
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0
#np_x[cond1]
np_x[cond1 & cond2]

# If you need "or" use |

np_x[cond1 & cond2 | cond3]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Broadcasting

In [7]:
'''
- Slicing, fancy indexing
- Masking
- Broadcasting

Basically numpy behaves like vectors

[1,        [5, 
 2, x 5 =   10, 
 3]         15]


'''

np_x = np.random.randint(10, size = 10) #10 is exclisive
np_x

array([0, 0, 3, 8, 3, 8, 8, 7, 0, 7])

In [8]:
np_x * 3

array([ 0,  0,  9, 24,  9, 24, 24, 21,  0, 21])

In [9]:
some_list = [1,2,3]
some_list * 3 # Not use lists in DS therefore

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [10]:
#Create an array

np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.arange(3) 

array([0, 1, 2])

In [12]:
#What whould happen?


np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [13]:
x = np.arange(3)
x

array([0, 1, 2])

In [14]:
x.shape

(3,)

In [15]:
#Make x a column vector
x = x.reshape(3,1)
x

array([[0],
       [1],
       [2]])

In [16]:
#Why do we call it a column vector ==> column dimevsion, is 1

In [17]:
x

array([[0],
       [1],
       [2]])

In [18]:
y = np.arange(3)
y

array([0, 1, 2])

In [19]:
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [20]:
#First create a numpy matrix of size 2, 3

#np.ones()
#np.empty()
#np.zeros()
#np.diagonal()

'''
[1, 1, 1],
[1, 1, 1]
'''

np_x = np.ones((2,3)) # ones - fn input is a tuple
print(np_x)

#Veryfy shape
np_x.shape


[[1. 1. 1.]
 [1. 1. 1.]]


(2, 3)

In [21]:
# Reshape to 3,2

np_y = np_x.reshape(3, 2) # Reshape - fn input is a tuple
print(np_y)

#Verify shape
np_y.shape

[[1. 1.]
 [1. 1.]
 [1. 1.]]


(3, 2)

In [22]:
#Add [1,2] to each row
np_z = [1,2]

np_y + np_z

array([[2., 3.],
       [2., 3.],
       [2., 3.]])

In [23]:
#Numpy array 1 size (3,2)
x = np.ones((3,2))
print(f"x: {x} \n")

#Numpy array 2 size (3,)
y = np.ones((3,))
print(f"y: {y}")

#Try to add - Error
#x + y

#Reshape
y = y.reshape((3,1))
print(f"y reshaped : {y}")

print(x + y)

x: [[1. 1.]
 [1. 1.]
 [1. 1.]] 

y: [1. 1. 1.]
y reshaped : [[1.]
 [1.]
 [1.]]
[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [24]:
y = np.ones((3,))
print(f"y: {y}")

#Reshape
x = x.reshape((2,3))
print(f"x reshaped : {x}")


print(x + y)

y: [1. 1. 1.]
x reshaped : [[1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]]


Task 

1. Create a numpy array of size 200 by 4 with random float values between 1 to 5 and name it Data

2. Split the array into two numpy arrays, X and y, where the X contains the first 3 columns and y contains the last column.

3. Continuing, split the first 70% of the 200 rows(140) of X and y and call them X_train and y_train. Similarly, populate X_test and y_test using same corresponding columns but 30% rest of the data(60 rows).


In [25]:
# 1
np_array = np.ones((200,4))
X = np_array[0:200,0:3]
X.shape



(200, 3)

In [26]:
y = np_array[0:200,[3]]
y.shape

(200, 1)

In [27]:
# If we are not selecting a random sample
index = int(0.7 * np_array.shape[0])
index

140

In [28]:
x_test = X[0:index,0:3 ]
x_test.shape

(140, 3)

In [29]:
y_test = y[0:index, 0]
y_test.shape

(140,)

In [30]:
#np.ones((200,4))

#np.random.randint(low, high, shape_tuple)

data0 = np.random.randint(0, 10, (200,4))

#np.random.uniform(low, high, shape_tuple)

data = np.random.uniform(1, 10, (200,4))

print(data.shape)

#Verify
data.max()
data.min()


(200, 4)


1.0056668558226027

In [31]:
# First 3 columns becomes X ==> Slicing

X = data[:,0:3] # data[dim1, dim2] ot data[:,:3], data[:,:-1]

y = data[:, 3]

#(200, ) - 1 Dimension
#(200, 1) - 2 Dimension

X.shape, y.shape



((200, 3), (200,))

In [32]:
#X_train contains 70% rows of X

dataset_size  = X.shape[0]
dataset_size

train_size = int(dataset_size * 0.7) # ==>This is float without int()
train_size

x_train = X[:train_size , : ]
x_test = X[train_size:  , : ]

x_train.shape, x_test.shape

# This is not the right way.




((140, 3), (60, 3))

In [33]:
import random

my_list = range(200)
random_140_samples = random.sample(my_list, train_size)
len(random_140_samples)
#random_140_samples

140

In [34]:
x_train = X[random_140_samples, :] 
x_train.shape

(140, 3)

In [35]:
# x_test should take only the inverse of random_140_samples --> list comprehension

next_60_indexes_not_in_this_140 = [ i for i in range(200) if i not in random_140_samples] 
len(next_60_indexes_not_in_this_140)

60

In [36]:
x_test = X[next_60_indexes_not_in_this_140, :]
x_test.shape

(60, 3)

In [37]:
y_train = y[random_140_samples] 
y_train.shape

(140,)

In [38]:
y_test = y[next_60_indexes_not_in_this_140]
y_test.shape

(60,)

In [39]:
# 1. Now X_train is (140, 3) create non-overlapping data of shape (14,3) --> use the for loop
#2. Please create a subset of X_Train of size 50, which the starting point is randomized
# If the number has exceeded, take only what you have - Mini - Batch


batch_list = []

batch_size = 14

for i in range(0, train_size, batch_size):
    k = x_train[i:i+batch_size, :]
    batch_list.append(k)

len(batch_list) ,   batch_list[0].shape

(10, (14, 3))

In [40]:
'''
first = X[0:14]
second = X[14:28]
...
last = X[126:]

Strating index --> 0, 14, 28,...
End index --> 14, 28, 42, ...
'''

for i in range(0, 140, 14):
    X[i:i+14]


In [41]:
x_train.shape

(140, 3)

In [42]:
#2. Please create a subset of X_Train of size 50, which the starting point is randomized

# some_subset = X[ random_start : random_start+50 ]

random_num = random.choice( range(200) )
some_subset = x_train[ random_num : random_num+50, : ]
some_subset.shape


(0, 3)

In [43]:
#Task 

#1. Numpy array 150 by 5, Imagine this holds 150 samples of height, weight, age, salary, GPA

#3. Split the X into X_train and X_test where x_train contains 70% of the data and split y in to y_train and y_test, where y_train contains 70% of the data


In [44]:
data = np.random.uniform(1, 10, (150,5))

#Verify
print(data.shape, data.max(), data.min())

(150, 5) 9.999573167143652 1.0376073596281383


In [45]:
#2. Split the array of the first four columns into a variable called X and the last column by y

X = data[:,0:4] # data[dim1, dim2] or data[:,:3], data[:,:-1]

y = data[:, 4]

print(X.shape, y.shape)

(150, 4) (150,)


In [49]:
#3. Split the X into X_train and X_test where x_train contains 70% of the data and split y in to y_train and y_test, where y_train contains 70% of the data

#X_train and y_train contains 70% rows of X

dataset_size  = X.shape[0]
train_size = int(dataset_size * 0.7) 
print(dataset_size,train_size)

my_list = range(150)
random_105_samples = random.sample(my_list, train_size)
len(random_105_samples)
x_train = X[random_105_samples, :] 
y_train = y[random_105_samples]
print(x_train.shape, y_train.shape)



150 105
(105, 4) (105,)


In [54]:
# x_test should take only the inverse of random_140_samples --> list comprehension

next_45_indexes_not_in_this_105 = [ i for i in range(150) if i not in random_105_samples] 
len(next_45_indexes_not_in_this_105)

x_test = X[next_45_indexes_not_in_this_105, :]


y_test = y[next_45_indexes_not_in_this_105]

print(x_test.shape, y_test.shape)

(45, 4) (45,)


In [58]:
#4. Create 10 non-overlapping dataset of X_train
batch_list = []
num_sets = 10

batch_size = int(train_size / num_sets)

print(batch_size)

for i in range(0, train_size, batch_size):
    k = x_train[i:i+batch_size, :]
    batch_list.append(k)

len(batch_list) ,   batch_list[0].shape

10


(11, (10, 4))