# Programming for Data Science and Artificial Intelligence

## Numpy

In [1]:
#numpy is list
#because 
#   1. numpy is faster
#   2. numpy has more built-in functions that facilitate data science

#to start using numpy

#conda install numpy
#pip install numpy

import numpy as np

In [3]:
#create your first list
python_list = [1, 2, 3]

#convert this list to numpy list
numpy_list = np.array(python_list)

type(numpy_list)

numpy.ndarray

In [4]:
#one theory: one numpy array can only support one type of data

#but python list can support many types of data in one list
my_list = [1, "Hello", True, 1.0]

In [5]:
my_list = [1, 2, 3, 4.5]

np_list = np.array(my_list)

np_list

array([1. , 2. , 3. , 4.5])

In [72]:
#i can of course convert the type using numpyarray.astype()

np_list_int = np_list.astype(int)

np_list_int

array([1, 2, 3, 4])

Accessing and indexing

In [73]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])  #x = np.array(range(1, 9))

In [74]:
#1st way: using index      so how do get 3
x[2]

3

In [75]:
#2nd way - slicing - get more than one members
#format array[start:end:step] --> end is exclusive

x[0:3]

array([1, 2, 3])

In [76]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
#get 3 - 8

#3 ways

##1st way
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [78]:
##2nd way
x[2:]

array([3, 4, 5, 6, 7, 8])

In [79]:
##3rd way - so no
x[2:-1]

array([3, 4, 5, 6, 7])

In [80]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
#get 7, 8 using minus
x[-2:]

array([7, 8])

In [82]:
#3rd way - fancy indexing
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
#sometimes, i want element index 2 and 4
x[2], x[4]

(3, 5)

In [84]:
#put a list of index you wanna access
x[  [2, 4]  ]

array([3, 5])

2D arrays

<center><img src="../figures/02.03-numpy-matrix-indexing.png" width=500/></center>

In [85]:
data = [[1, 2], [3, 4], [5, 6]]

np_list = np.array(data)

np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
#format when you are dealing with multi-dimensional array
#array[dim1, dim2, so on.......]

data

[[1, 2], [3, 4], [5, 6]]

In [87]:
np_list[0, 1]

2

In [88]:
#can you guys retrieve 6 for me

np_list[2, 1]

6

In [89]:
#can you guys get [3, 4], [5, 6]

# np_list[firstdim, secondim]

#1st way: slicing
np_list[ 1: , :]  #if you put [1:3, :]

array([[3, 4],
       [5, 6]])

In [90]:
data

[[1, 2], [3, 4], [5, 6]]

In [91]:
#2nd way: fancy indexing
np_list[ [1, 2] , : ]

array([[3, 4],
       [5, 6]])

In [92]:
#3rd way: the last two

np_list[-2: , :]

array([[3, 4],
       [5, 6]])

In [93]:
data

[[1, 2], [3, 4], [5, 6]]

In [94]:
#chaky, how do i know which dimension is which
np_list[0, ]

array([1, 2])

In [95]:
np_list[: , 0]

array([1, 3, 5])

In [96]:
data

[[1, 2], [3, 4], [5, 6]]

In [97]:
#get 1, 3
np_list[0:2, 0]

#get 1, 5

#1st way: fancy indexing
np_list[   [0, 2] , 0    ]

array([1, 5])

In [99]:
#2nd way: recall the format start:end:step

np_list[           0::2  , 0       ]

array([1, 5])

17:50 - 18:00

In [100]:
x = [
    
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
    
]

np_list = np.array(x)

#1:  get 2, 6, 10, 14
np_list[:, 1]

#2:  get 7, 11
np_list[1:3, 2]

#3:  get 4, 7, 10   - hint: use fancy indexing on both dimensions
np_list[ [0, 1, 2] , [3, 2, 1]]

#4:  get 16, 15, 14, 13  - hint: use step -1

np_list[-1, -1::-1]

array([16, 15, 14, 13])

In [33]:
#fun exercise you can do at home :-):

#given a matrix = [ [99, 99, 99], 
#                   [99, 99, 99], 
#                   [99, 99, 99]]

#imagine 99 is empty
#assume 1 is X
#assume 0 is O

#get the input from the X side and O side alternatively
#give you a tupe of index

#if X side input (0, 0)
#then the matrix becomes 

#                 [ [X, 99, 99], 
#                   [99, 99, 99], 
#                   [99, 99, 99]]

#if O side input also (0, 0)
#alert them to input again
#otherwise, fill the matrix

#challenge (optional): if the first one to get three in row, stop the game

Afternoon exercise

In [34]:
y = [
    
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    
]

np_y = np.array(y)

#try to get

#1. 4, 5, 6
#2. 2, 5
#3. 3, 4
#4. 9, 6, 3

In [35]:
#1

#format:  y[row, col]  or  y[dim1, dim2]

np_y[1, :]


array([4, 5, 6])

In [36]:
np_y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
#2. I want 2, 5

#4, 5 ==> row 0 and 1,  col 1

#format: np_y[row, col]

np_y[   [0, 1]  ,  1 ]  #1st way

np_y[   0:2     ,  1 ]  #2nd way - use slicing

array([2, 5])

In [38]:
#3. 3, 4

#row ==> 0 and 1
#col ==> 2 and 0

row = [0, 1]
col = [2, 0]

np_y[row, col]

array([3, 4])

In [39]:
np_y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
#4. 9, 6, 3

#row 2, 1, 0
#col 2

#1st fancy indexing
row = [2, 1, 0]
col = [2]

np_y[row, col]

#2nd slicing

np_y[    2:0:-1    ,     2   ]


array([9, 6])

Masking

In [41]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#i want only even number

#1st way: if

even = []

for num in x:
    if num % 2 == 0:
        even.append(num)
        
#2nd way: list comprehension

even = [ num for num in x if num % 2 == 0]

even

[2, 4, 6, 8, 10]

In [42]:
#do you guys feel painful to write such code!?

np_x = np.arange(10)  #this is basically range(10) but for numpy

np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np_x[  np_x % 2 == 0   ]

#actually this guy np_x % 2 == 0 is fancy indexing

array([0, 2, 4, 6, 8])

In [44]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [45]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
ix = [True, True, False, False, True, True, True, False, False, True]

np_x[ix]

array([0, 1, 4, 5, 6, 9])

In [47]:
#choose odd number

np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[       cond1  & cond2  | cond3       ]  #if you want "or", use |

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Broadcasting

In [49]:
'''
- slicing, fancy indexing
- masking
- broadcasting
'''

#basically, numpy behaves like vectors

'''
[1,            [5
 2,  x   5   =  10
 3]             15]
'''

'\n[1,            [5\n 2,  x   5   =  10\n 3]             15]\n'

In [50]:
np_x = np.random.randint(10, size = 10)  #10 is exclusive

np_x

array([4, 9, 2, 6, 9, 5, 2, 9, 0, 0])

In [51]:
np_x * 3

array([12, 27,  6, 18, 27, 15,  6, 27,  0,  0])

In [52]:
#create a np array

np.ones((3, 3))  #np.ones is to create a matrix of ones, with the specified size

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.arange(3)

array([0, 1, 2])

In [54]:
#what would happen if I do

np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [55]:
x = np.arange(3)
x

array([0, 1, 2])

In [56]:
x.shape

(3,)

In [57]:
#i gonna make this as a column vector

#btw, why do i called this column vector?

#because at the column dimension, is 1

x = x.reshape(     (3, 1)     )

x

array([[0],
       [1],
       [2]])

In [58]:
x

array([[0],
       [1],
       [2]])

In [59]:
y = np.arange(3)
y

array([0, 1, 2])

In [60]:
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [61]:
#first, create a numpy matrix of ones of size 2, 3

my_mat = np.ones(       (2, 3)     )   #np.zeros, np.empty, np.diagonal

'''
[
[1, 1, 1],
[1, 1, 1]
]
'''

#second, verify the shape using .shape
print(f"Before: {my_mat.shape}")

#third, i want you to reshape to 3, 2, and verify the shape
my_mat = my_mat.reshape(    (3, 2)   )
print(f"After: {my_mat.shape}")

#fourth, i want you to add [1, 2] to each row
add = [1, 2]
my_mat = my_mat + add

my_mat

Before: (2, 3)
After: (3, 2)


array([[2., 3.],
       [2., 3.],
       [2., 3.]])

In [62]:
#Create two numpy array

#first one is size (3, 2) - any number
x = np.ones(     (3, 2)   )

x = x.reshape(   (2, 3)  )

#second one is size (3, ) - any number
y = np.ones(     (3,  )   )  #==> (1, 3)

# y = y.reshape(   (3, 1)       )

#try to add them but you will find error
x + y  #final shape will be (3, 2)

#hint: fix it using reshape so they can be added

array([[2., 2., 2.],
       [2., 2., 2.]])

Break: 14:27 - 14:37

Task

1. Create a numpy array of size 150 by 5.  Imagine this array holds 150 samples of students height, weight, age, salary, GPA

2. Split the array of the first four columns into a variable called X , and the last column to y

3. Split the X into X_train and X_test, where X_train contains 70% of the data, and split the y into y_train and y_test, where y_train contains 70% of the data
   
4. Create 10 non-overlapping dataset of X_train 

In [63]:
data = np.random.uniform(0, 10, (150, 5))
data.shape

(150, 5)

In [64]:
X = data[:, :-1]
y = data[:, -1]

X.shape, y.shape

((150, 4), (150,))

In [65]:
#1st easy way

dataset_size = X.shape[0]
print(f"whole dataset size:  {dataset_size}")

train_size  = int(dataset_size * 0.7)
print(f"train size:  {train_size}")

X_train = X[:train_size]
X_test  = X[train_size:]

X_train.shape, X_test.shape


whole dataset size:  150
train size:  105


((105, 4), (45, 4))

In [66]:
#2nd way

#randomized way

#randomly pick 105 numbers from 0 to 150

my_list = range(0, 150) #create a list of 0 to 149

random_train_idx = random.sample(my_list, train_size)

len(random_train_idx)

X_train = X[random_train_idx]

aside_train_idx = [num for num in range(150) if num not in random_train_idx]

X_test  = X[aside_train_idx]

X_train.shape, X_test.shape

#which will be useful when you learn "stochastic gradient descent" and "minibatch gradient descent"


NameError: name 'random' is not defined

In [ ]:
X_train.shape

(105, 4)

In [ ]:
split = X_train.shape[0] // 10

split

10

In [ ]:
for counter in range(0, X_train.shape[0], split):
    print(X_train[counter:counter+split].shape)

(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(5, 4)


In [ ]:
#1. to create, many ways 

#np.ones(  (200, 4)  )
#np.zeros( (200, 4)  )
#np.random.randint(0, 10,    (200, 4)  )  #create a numpy array of shape (200, 4) with numbers between 0 and 9
#np.random.uniform(1, 10,    (200, 4)  )

data = np.random.uniform(1, 10,    (200, 4)  )

data.shape
data.max()
data.min()

#2. first three columns = X, and the last = y
#format: np_array[row, col]
X = data[:, 0:3]  #or [:, :3] or [:, :-1]
y = data[:, -1]

X.shape, y.shape

#3. X_train contains 70% rows of X

dataset_size = X.shape[0]
dataset_size

train_size = int(dataset_size * 0.7)  #==>this train_size will become type "float"

train_size

X_train = X[  :train_size   ,      :       ]
X_test  = X[  train_size:   ,      :       ]


#this is not the right way

# X_train = X[   [1, 5, 100, 170, 4, 22, ......]                        ]



In [ ]:
import random

my_list = range(200)

random_140_indexes = random.sample(my_list, train_size)

len(random_140_indexes)

140

In [ ]:
X_train = X[   random_140_indexes   ,  :   ]
X_train.shape

(140, 3)

In [ ]:
next_60_indexes_not_in_this_140 = [  i  for i in range(200)  if i not in random_140_indexes    ]

len(next_60_indexes_not_in_this_140)

X_test = X[   next_60_indexes_not_in_this_140   ,  :   ]

X_test.shape

(60, 3)

In [ ]:
'''
first  = X[0:14]
second = X[14:28]
...
...
last   = X[126:]
'''

#how do get 0, 14, 28, 42.....140

# for i in range(10):
#     my_list.append(i * 14)

for i in range(0, 140, 14):
    print(X[i:i+14])  #do whatever append you want

[[1.11764591 5.28759748 2.46244232]
 [1.39432325 1.44040313 1.99463061]
 [8.70886322 1.1563082  9.61024842]
 [8.67898306 8.37858285 7.43819246]
 [2.22224377 1.88614691 8.27207334]
 [5.67782144 6.45034473 7.78157194]
 [1.43676154 2.35983378 8.90354576]
 [4.80548677 6.94825814 2.66256311]
 [4.89204887 1.40395816 8.14856486]
 [6.58820384 3.05420692 1.52230588]
 [9.46878041 4.68438776 7.73106235]
 [9.45661017 5.51554142 7.65988619]
 [6.12100613 2.53095928 8.79401162]
 [1.48419902 4.00904441 7.31576843]]
[[9.6500925  5.46479003 4.2069474 ]
 [2.08407802 9.89196359 9.62286259]
 [4.36557619 8.5321495  7.06624637]
 [5.68279659 1.05307732 7.69641619]
 [3.5236216  4.57135683 5.52115378]
 [9.70483696 7.73022284 9.41279443]
 [2.70042929 4.20931048 5.72425917]
 [1.22690886 3.68001597 7.62071497]
 [2.3264321  9.01394884 4.09294945]
 [2.46731289 3.95528375 6.06690707]
 [6.18419775 1.75212325 5.16110062]
 [2.65209158 9.44965044 8.66341734]
 [8.86516329 8.98873549 7.90594564]
 [4.83068665 3.1769952  5.3

In [ ]:
X_train.shape

(140, 3)

In [ ]:
#2. Please create a subset of X_train of size 50, which the starting point is randomized.  

random_num = random.choice(  range(200) )

some_subset = X_train[  random_num:random_num+50  ]

some_subset.shape


(50, 3)

In [ ]:
#1. Now my X_train is (140, 3), please create ten non-overlapping data of shape (14, 3) --> use for loop
#2. Please create a subset of X_train of size 50, which the starting point is randomized.  
#   If the number exceeds, take only what you have

#  this is part of something called mini-batch gradient descent, and it's essential to every deep learning